[package]
name = "oci-registry"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
oci-spec = { version = "0.5.1" }
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.11.0", features = ["fs"] }
